# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  terraform: 'circleci/terraform@1.2'
jobs:
  terraplan:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: .
      - terraform/validate:
          path: .
      - terraform/fmt:
          path: .
      - terraform/plan:
          path: .
    # working_directory: ~/src
  terrascan:
    docker:
      - image: accurics/terrascan:latest
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            /go/bin/terrascan scan -o json
  kibit:
    docker:
      - image: clojure:openjdk-8
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            echo "{:user {:plugins [[lein-kibit \"0.1.8\"]]}}" > ~/.lein/profiles.clj
            lein kibit .
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  security:
    jobs:
      - terrascan
      - kibit
  verify:
    jobs:
      - terraplan
